server:
  port: 8080

spring:
  application:
    name: aitesting-back
  datasource:
    url: jdbc:mysql://159.138.135.69:3306/aitesting?useSSL=true
    username: our
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    openai:
      api-key: #模型API密钥
      base-url: #模型提供商API地址
      chat:
        options:
          model: #可用模型
    mcp:
      server:
        stdio: false
        name: TestAssistantMcp
        version: 1.0.0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#spring事务管理日志
logging:
  level:

    # MyBatis Mapper层SQL日志
    com.example.aitestingback.Mapper: TRACE

    org.springframework.jdbc.support.JdbcTransactionManager: debug


